kind: pipeline
name: default

# Pipeline for putting cloudformation files into S3 for nested stacks
steps:
  - name: docker push
    image: plugins/docker
    settings:
      repo: eignhpants/image-builder
      username:
        from_secret: dh-username
      password:
        from_secret: dh-pw
    publish:
      image: eignhpants/go-image-builder
